using System;
using System.Drawing;
using System.Windows.Forms;
using AplikasiPerpustakaanSiJess.Models;
using AplikasiPerpustakaanSiJess.UI;

namespace AplikasiPerpustakaanSiJess.UI.Forms
{
    public class IdCardForm : Form
    {
        Anggota data;
        PictureBox preview;
        Button btnSave;

        public IdCardForm(Anggota a)
        {
            Theme.ApplyForm(this);
            data = a;

            Text = "ID Card Anggota";
            Width = 420; Height = 300;
            StartPosition = FormStartPosition.CenterParent;
            BackColor = Theme.Bg;

            preview = new PictureBox { Left = 20, Top = 20, Width = 360, Height = 180, SizeMode = PictureBoxSizeMode.Zoom, BackColor = Color.White };
            btnSave = new Button { Text = "Save PNG", Left = 20, Top = 215, Width = 360, Height = 32, BackColor = Theme.Primary, ForeColor = Color.White, FlatStyle = FlatStyle.Flat };
            btnSave.FlatAppearance.BorderSize = 0;

            Controls.Add(preview);
            Controls.Add(btnSave);

            preview.Image = RenderCard();

            btnSave.Click += (_, __) =>
            {
                // Mengubah using var menjadi using block
                using (SaveFileDialog sfd = new SaveFileDialog { Filter = "PNG Image|*.png", FileName = "ID_" + data.NamaLengkap + ".png" })
                {
                    if (sfd.ShowDialog() == DialogResult.OK)
                    {
                        preview.Image.Save(sfd.FileName);
                        MessageBox.Show("Berhasil disimpan.");
                    }
                }
            };
        }

        Bitmap RenderCard()
        {
            Bitmap bmp = new Bitmap(720, 360);
            // Menggunakan using block bertingkat untuk GDI+ objects
            using (Graphics g = Graphics.FromImage(bmp))
            {
                g.Clear(Color.White);

                using (SolidBrush p = new SolidBrush(Theme.Primary))
                {
                    g.FillRectangle(p, 0, 0, 720, 80);
                }

                // Kita bisa menumpuk using jika tipenya sama untuk merapikan kode
                using (Font f1 = new Font("Segoe UI", 18, FontStyle.Bold))
                using (Font f2 = new Font("Segoe UI", 12, FontStyle.Regular))
                using (Font f3 = new Font("Segoe UI", 10, FontStyle.Italic))
                using (SolidBrush white = new SolidBrush(Color.White))
                using (SolidBrush dark = new SolidBrush(Theme.Text))
                using (SolidBrush muted = new SolidBrush(Theme.Muted))
                {
                    g.DrawString("SiJess Library", f1, white, 18, 18);

                    g.DrawString("ID Anggota", f2, dark, 18, 95);
                    g.DrawString("Nama : " + data.NamaLengkap, f2, dark, 18, 130);

                    string nikDisplay = string.IsNullOrWhiteSpace(data.NikOrNis) ? "-" : data.NikOrNis;
                    g.DrawString("NIK/NIS : " + nikDisplay, f2, dark, 18, 160);

                    g.DrawString("JK : " + data.JenisKelamin, f2, dark, 18, 190);
                    g.DrawString("Telp : " + data.NoTelp, f2, dark, 18, 220);

                    g.DrawString("Generated by Aplikasi Perpustakaan SiJess", f3, muted, 18, 300);
                }
            }

            return bmp;
        }
    }
}